### ISSUE TITLE
之前pr里面的问题（模糊效果）仍未解决（还没提交的话请忽略此项），以及各种其他的离谱BUG

### ISSUE THREAD

**Issue by TotoWang-hhh** [HanHan233/phigros-html5#11]
# 运行环境

- 设备：Dell一体机
- 设备平台：Windows
- 浏览器：FireFox 96.0.1 (32 位)     （UA找不到）

- 错误现象： 之前pr里面的问题（模糊效果）仍未解决（还没提交的话请忽略此项），以及各种其他的离谱BUG，详见图片：
![图片](https://user-images.githubusercontent.com/67090055/149928328-5eb0538e-9405-4200-8633-a6bcf05a94c8.png)
![图片](https://user-images.githubusercontent.com/67090055/149928385-b54d2996-a06b-46ba-b738-eb4c938feaa0.png)

- 错误Log：我觉得应该不需要吧：）

**Comment by HanHan233** [comment]
这个已经再改了

**Comment by HanHan233** [comment]
已修复，请尝试清除浏览器数据并重新加载查看效果

**Comment by HanHan233** [comment]
正式修复咯，大部分界面应该都有模糊了吧
