### ISSUE TITLE
选关界面布局错乱

### ISSUE THREAD

**Issue by TotoWang-hhh** [HanHan233/phigros-html5#12]
# 运行环境

- 设备：iPhone XS
- 设备平台：iOS 15.2

- 浏览器：Safari iOS 15.2 自带版本 （其他信息未知）

- 错误现象：选关界面布局错乱
- 复现：点击屏幕进入选章节界面 > 点击《单曲 精选集》的PLAY > 选关界面屏幕布局错乱+部分内容无法显示+没有关卡
![IMG_6397](https://user-images.githubusercontent.com/67090055/150069767-a679321f-76bf-4174-b5c2-53298df00c8e.PNG)

- 错误Log：难不成我为了看这个去整台Mac？？

**Comment by HanHan233** [comment]
尝试使用无痕模式或者清除浏览数据后访问，我这里是正常的
![image](https://user-images.githubusercontent.com/64469437/150072960-9d79e078-62c7-4bbc-b489-97f5ba2c96ee.png)

**Comment by TotoWang-hhh** [comment]
加载起来非常的慢啊

**Comment by TotoWang-hhh** [comment]
还是有问题，不过关卡已经能够正常显示了。
![image](https://user-images.githubusercontent.com/67090055/150124509-11cd17a4-1614-4b16-a295-aa0990d5f150.png)
