### ISSUE TITLE
主界面设置图标缺失+主界面中间出现小黑点

### ISSUE THREAD

**Issue by TotoWang-hhh** [HanHan233/phigros-html5#14]
# 运行环境

- 设备：iPhone XS
 
- 设备平台：iOS 15.2

- 浏览器：Safari iOS 15.2 自带版本 （其他信息未知）

- 错误现象：主界面设置图标缺失+主界面中间出现小黑点（所有平台皆有小黑点）
- 复现：单击屏幕进入选章节界面 > 主界面设置图标缺失+主界面中间出现小黑点
![IMG_6399(20220119-134310)](https://user-images.githubusercontent.com/67090055/150071169-621c0742-cc76-4609-8894-f8dad88ad066.PNG)

- 错误Log：无法查看

**Comment by HanHan233** [comment]
尝试使用无痕模式或者清除浏览数据后访问，我这里是正常的
![image](https://user-images.githubusercontent.com/64469437/150072541-85f6987a-ab2e-4aaf-8b91-641aa15756fa.png)

**Comment by TotoWang-hhh** [comment]
> 尝试使用无痕模式或者清除浏览数据后访问，我这里是正常的 ![image](https://user-images.githubusercontent.com/64469437/150072541-85f6987a-ab2e-4aaf-8b91-641aa15756fa.png)

一般来讲，Safari连着刷新几次就会同步成网页最新状态，可是这里没用

**Comment by TotoWang-hhh** [comment]
另外，背景也卡没了

**Comment by TotoWang-hhh** [comment]
初步怀疑小黑点是加载失败的背景

**Comment by HanHan233** [comment]
> 初步怀疑小黑点是加载失败的背景

否定，小黑点是设置按钮

**Comment by HanHan233** [comment]
很明显是CSS版本过老造成

**Comment by TotoWang-hhh** [comment]
垃圾Safari，毁我Phigros
：（

**Comment by HanHan233** [comment]
![Uploading image.png…]()
了解一下

> > 尝试使用无痕模式或者清除浏览数据后访问，我这里是正常的 ![image](https://user-images.githubusercontent.com/64469437/150072541-85f6987a-ab2e-4aaf-8b91-641aa15756fa.png)
> 
> 一般来讲，Safari连着刷新几次就会同步成网页最新状态，可是这里没用

**Comment by TotoWang-hhh** [comment]
> ![image](https://user-images.githubusercontent.com/64469437/150073517-ecc6bd26-a556-49e4-b2fc-251a2e789a4c.png) 了解一下
> 
> > > 尝试使用无痕模式或者清除浏览数据后访问，我这里是正常的 ![image](https://user-images.githubusercontent.com/64469437/150072541-85f6987a-ab2e-4aaf-8b91-641aa15756fa.png)
> > 
> > 
> > 一般来讲，Safari连着刷新几次就会同步成网页最新状态，可是这里没用

前面几次会取本地缓存，这个速度能区分，连续刷新3次左右就重新加载
