### ISSUE TITLE
将此项目搬运到服务器上后，进入音频测试页单击超链接会出现404

### ISSUE THREAD

**Issue by TotoWang-hhh** [HanHan233/phigros-html5#15]
# 运行环境

- 设备：Infinity Free 云服务器 + Windows PC 版 FireFox 96.0.1 (32 位)

- 设备平台：服务器（未知，无法远程且无相关信息），电脑：Windows 10 20H2

- 浏览器：Windows PC 版 FireFox 96.0.1 (32 位)     UA找不到

- 错误现象：进入镜像站rgzz.great-site.net/phigros > 点击链接进入网页版Phigros > 看到404页面

- 错误Log：稍后附上

**Comment by HanHan233** [comment]
你这得放到根目录里啊

**Comment by TotoWang-hhh** [comment]
> 你这得放到根目录里啊

。。。有个东西叫做相对路径：）

**Comment by HanHan233** [comment]
但我就是懒得写啊，我在子目录的时候你让我怎么***方便地***获取跟路径嘛

**Comment by HanHan233** [comment]
我都是`location.href="../path/to/index.html"`的

**Comment by TotoWang-hhh** [comment]
"../taptostart/index.html"这样应该行吧：）

**Comment by HanHan233** [comment]
？什么意思

**Comment by TotoWang-hhh** [comment]
就是上一层目录下的TapToStart文件夹下的index.html

**Comment by HanHan233** [comment]
../就是从根目录开始计算的相对目录，比如`../index.html`就是`rgzz.great-site.net/index.html`、`../tapToStart/index.html`就是`rgzz.great-site.net/tapToStart/index.html`

**Comment by TotoWang-hhh** [comment]
> ../就是从根目录开始计算的相对目录，比如`../index.html`就是`rgzz.great-site.net/index.html`、`../tapToStart/index.html`就是`rgzz.great-site.net/tapToStart/index.html`

编程语言不同带来的麻烦吧。。。
Python里面../指的上级目录😂

**Comment by HanHan233** [comment]
你也可以把所有的`../`替换为`../phigros/`尝试解决问题
