### ISSUE TITLE
点击开始界面加载很慢，而且加载完成前无法进入游戏

### ISSUE THREAD

**Issue by TotoWang-hhh** [HanHan233/phigros-html5#16]
# 运行环境

- 设备：![image](https://user-images.githubusercontent.com/67090055/150261293-ca640646-8abf-4020-b762-0fe0e0a72716.jpeg)

- 浏览器：Safari iOS15.2 自带

- 错误现象：见标题

- 建议：优先加载点击跳转的代码

刚刚在上课:)

**Comment by HanHan233** [comment]
我现在改成DOMContentLoaded了，你重置浏览器看看有没有好点
