### ISSUE TITLE
手机选择关界面仍然错乱，不过可以正常选关

### ISSUE THREAD

**Issue by TotoWang-hhh** [HanHan233/phigros-html5#17]
# 运行环境

- 设备：![image](https://user-images.githubusercontent.com/67090055/150270064-4feaee57-50fc-4148-9237-893e7eb67e10.jpeg)

-Safari iOS 15.2 自带版本

- 错误现象：见标题，图片供参考
![image](https://user-images.githubusercontent.com/67090055/150270156-9022bdd6-4165-425b-80ef-97bb8b083fbf.png)

**Comment by HanHan233** [comment]
正常，懒得想算法了
