### ISSUE TITLE
加载界面难度无法正常显示

### ISSUE THREAD

**Issue by TotoWang-hhh** [HanHan233/phigros-html5#18]
# 运行环境

- 设备：
![image](https://user-images.githubusercontent.com/67090055/150270319-57a4c359-5702-4ebc-90a1-b7a05cc7297b.jpeg)

- 浏览器：看前面报的issue吧

- 错误现象：见标题（手机真的不好打字），图片供参考
![image](https://user-images.githubusercontent.com/67090055/150270410-258f26c0-5e6f-4738-96c2-757140566ac0.png)

**Comment by HanHan233** [comment]
你访问[这里](https://pgr.han-han.xyz/loadingChartScreen/index.html?c=sample&l=ez)，建议无痕模式

**Comment by HanHan233** [comment]
![image](https://user-images.githubusercontent.com/64469437/150271066-ebcd6b10-f025-4c7f-8cbb-4cb850bf6a49.png)
如无意外应该是这样的
