### ISSUE TITLE
关于黄键的一些小bug

### ISSUE THREAD

**Issue by luanmenglei** [HanHan233/phigros-html5#21]
在pc环境上，仅要点击一个黄键，并且鼠标保持跟随，就可以接下一串的黄键

**Comment by HanHan233** [comment]
啥意思，我听不太明白（

**Comment by TotoWang-hhh** [comment]
> 啥意思，我听不太明白（

我都懂了！就是说手机上黄键要按着才能接，但是电脑上只需要点一下第一个黄键，后面的拿鼠标跟着就能接。

另外就是提一下，触屏电脑如果用触屏玩的话，貌似就没有这个Bug

**Comment by HanHan233** [comment]
我拿新手教程测试了一下没这个问题啊
