### ISSUE TITLE
[Feature request] 是否考虑项目工程化？

### ISSUE THREAD

**Issue by jiazengp** [HanHan233/phigros-html5#24]

**Comment by HanHan233** [comment]
细说，我觉得应该是个好提议，但是至于工程化之后我能不能拿捏住就是另一个问题了（

**Comment by jiazengp** [comment]
包括 CI，CD，规范化，组件化，模块化，构建等等。
确实可能需要一定的 Node 和一些构建工具的基础，但是总的来说并不难。
如果你觉得不错我可以提 pr。

**Comment by HanHan233** [comment]
要不加群说，GitHub我这推送不及时，群在我b站主页有

**Comment by jiazengp** [comment]
**ok**

**Comment by IcebearType** [comment]
可以集成chrome，自解压到系统temp文件夹，进度什么的存在appdata下

**Comment by HanHan233** [comment]
> 可以集成chrome，自解压到系统temp文件夹，进度什么的存在appdata下
> 

没必要，已经有pwa了，而且这种场景不适合

**Comment by HanHan233** [comment]
> 可以集成chrome，自解压到系统temp文件夹，进度什么的存在appdata下
> 

而且“工程化”不是打包

**Comment by TotoWang-hhh** [comment]
> 要不加群说，GitHub我这推送不及时，群在我b站主页有

我可以给你贡献一个论坛，你需要吗？只不过我网站挂掉了，需要点时间改域名了
