### ISSUE TITLE
使用代码检查工具

### ISSUE THREAD

**Issue by ZreXoc** [HanHan233/phigros-html5#4]
在阅读源码时，我发现有许多并不符合规范的代码：

- `=`两端未使用空格分隔
- 单行代码过长(部分超过了140个字符)
- 使用`==`而非`===`
- 单双引号交替使用
- 句尾分号没有规范

这些问题导致代码缺少统一的标准，阅读、维护困难，并且有可能导致意外的错误

使用例如ESLint的代码检查工具可避免以上错误

**Comment by HanHan233** [comment]
收到，周二回家就检查检查，这玩意儿应该有vscode插件吧？
