### ISSUE TITLE
选关界面啥都没有

### ISSUE THREAD

**Issue by TotoWang-hhh** [HanHan233/phigros-html5#5]
自己看，不知道问题出在哪……
回去看看F12控制台
![image](https://user-images.githubusercontent.com/67090055/149872537-ef934c6a-b861-404a-bc0b-ac3be2665d08.png)![image](https://user-images.githubusercontent.com/67090055/149872538-11ae6cf6-ff11-4321-9d03-1d3f8355bf44.png)
![image](https://user-images.githubusercontent.com/67090055/149872548-0f3b0a89-786f-4af6-aaa5-3910e63924f3.png)

**Comment by HanHan233** [comment]
今日回去回档昨天的merge

**Comment by HanHan233** [comment]
等一下吧

**Comment by HanHan233** [comment]
已经修复
