### ISSUE TITLE
一个有关及时备份的建议

### ISSUE THREAD

**Issue by TotoWang-hhh** [HanHan233/phigros-html5#6]
看到Branch了吗？:)可以每次版本更新都建一个Branch，然后就以版本号命名，这样就可以做到及时备份

**Comment by HanHan233** [comment]
git本身就有备份功能，可以随时回档，此ISSUE将作废
<img width="316" alt="image" src="https://user-images.githubusercontent.com/64469437/149916446-a4dcb775-abde-4d2a-ace1-fb7712127cb8.png">
